java_test(
    name = "evaluator_test",
    srcs = ["EvaluatorTest.java"],
    test_class = "algebud.EvaluatorTest",
    deps = [
        "//core/java/algebud",
        "//core/java/algebud/token",
    ],
)
